name: instafirebase
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.0.dev <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - lib/assets/Screenshot 2023-09-21 105044.png
   - lib/assets/Screenshot 2023-09-21 194917.png
   - lib/assets/Screenshot 2023-09-21 195001.png
   - lib/assets/Screenshot 2023-09-21 195026.png
   - lib/assets/Screenshot 2023-09-21 195102.png
   - lib/assets/Screenshot 2023-09-21 195130.png
   - lib/assets/Screenshot 2023-09-21 222347.png

   - lib/assets/Screenshot 2023-09-21 235349.png
   - lib\assets\Screenshot 2023-09-21 235300.png
   - lib\assets\Screenshot 2023-09-21 235214.png
   - lib\assets\Screenshot 2023-09-21 235038.png
   - lib\assets\Screenshot 2023-09-21 234953.png
   - lib\assets\Screenshot 2023-09-21 234905.png
   - lib\assets\Screenshot 2023-09-21 234832.png
   - lib\assets\Screenshot 2023-09-21 234734.png
   - lib\assets\Screenshot 2023-09-21 234624.png
   - lib\assets\Screenshot 2023-09-21 234553.png
   - lib\assets\Screenshot 2023-09-22 121908.png
   - lib\assets\Screenshot 2023-09-22 131835.png 

  #  - lib\Screenshot 2023-09-24 171537 copy.png
   - lib\Screenshot 2023-09-24 171439.png
   - lib\Screenshot 2023-09-24 171428.png
  #  - lib\Screenshot 2023-09-24 171439 copy.png
  #  - lib\Screenshot 2023-09-24 171428 copy.png
   - lib\Screenshot 2023-09-24 171420.png
  #  - lib\Screenshot 2023-09-24 171420 copy.png
   - lib\Screenshot 2023-09-24 171400.png
  #  - lib\Screenshot 2023-09-24 171400 copy.png
   - lib\Screenshot 2023-09-24 171341.png
  #  - lib\Screenshot 2023-09-24 171341 copy.png
   - lib\Screenshot 2023-09-24 171331.png
  #  - lib\Screenshot 2023-09-24 171331 copy.png
   - lib\Screenshot 2023-09-24 171320.png
  #  - lib\Screenshot 2023-09-24 171320 copy.png
   - lib\Screenshot 2023-09-24 171238.png
  #  - lib\Screenshot 2023-09-24 171238 copy.png
   - lib\Screenshot 2023-09-24 171223.png
  #  - lib\Screenshot 2023-09-24 171223 copy.png
   - lib\Screenshot 2023-09-24 171208.png
  #  - lib\Screenshot 2023-09-24 171208 copy.png
   - lib\Screenshot 2023-09-24 171154.png
  #  - lib\Screenshot 2023-09-24 171154 copy.png
  #  - lib\Screenshot 2023-09-24 171154 copy 2.png      
   - lib\Screenshot 2023-09-24 171129.png
  #  - lib\Screenshot 2023-09-24 171129 copy.png
  #  - lib\Screenshot 2023-09-24 171120 copy.png
   - lib\Screenshot 2023-09-24 171120.png
   - lib\Screenshot 2023-09-24 171108.png
  #  - lib\Screenshot 2023-09-24 171108 copy.png
   - lib\Screenshot 2023-09-24 171057.png
  #  - lib\Screenshot 2023-09-24 171057 copy.png
   - lib\Screenshot 2023-09-24 171042.png
  #  - lib\Screenshot 2023-09-24 171042 copy.png
   - lib\Screenshot 2023-09-24 171029.png
  #  - lib\Screenshot 2023-09-24 171029 copy.png
   - lib\Screenshot 2023-09-24 170842.png
   - lib\Screenshot 2023-09-24 170842 copy.png
   - lib\Screenshot 2023-09-24 170824.png
   - lib\Screenshot 2023-09-24 170824 copy.png
   - lib\Screenshot 2023-09-24 170758.png
  #  - lib\Screenshot 2023-09-24 170758 copy.png
   - lib\Screenshot 2023-09-24 170747.png
   - lib\insideFeed\Screenshot 2023-09-24 171537.png
   - lib\insideFeed\Screenshot 2023-09-24 194313.png
   - lib\insideFeed\Screenshot 2023-09-24 194324.png
   - lib\insideFeed\Screenshot 2023-09-24 194334.png
   - lib\insideFeed\Screenshot 2023-09-24 194342.png
   - lib\insideFeed\Screenshot 2023-09-24 194402.png
   - lib\insideFeed\Screenshot 2023-09-24 194412.png
   - lib\insideFeed\Screenshot 2023-09-24 194431.png
   - lib\insideFeed\Screenshot 2023-09-24 194447.png
   - lib\insideFeed\Screenshot 2023-09-24 194456.png

   - lib\pitcures\Screenshot 2023-09-26 205710.png
  
   - lib\pitcures\Screenshot 2023-09-26 205722.png
   - lib\pitcures\Screenshot 2023-09-26 205748.png
   - lib\pitcures\Screenshot 2023-09-26 205825.png
   - lib\pitcures\Screenshot 2023-09-26 205833.png
   - lib\pitcures\Screenshot 2023-09-26 205855.png
   - lib\pitcures\Screenshot 2023-09-26 205902.png
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages