// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASbCI3Mj_QHSKogSE6aG97CIXjB7SL5kA',
    appId: '1:870228919490:web:4d106abc9b1b0fcdf8e75b',
    messagingSenderId: '870228919490',
    projectId: 'insta-pro-firebase',
    authDomain: 'insta-pro-firebase.firebaseapp.com',
    storageBucket: 'insta-pro-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVBX6vEpqUBNg7eEQv95OP9XRoAjjcgBM',
    appId: '1:870228919490:android:23ee80428cc3cccaf8e75b',
    messagingSenderId: '870228919490',
    projectId: 'insta-pro-firebase',
    storageBucket: 'insta-pro-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy3mIM5cmflGRuVFMzsRkivzWUI7MZVhU',
    appId: '1:870228919490:ios:5641f5c4becccfa3f8e75b',
    messagingSenderId: '870228919490',
    projectId: 'insta-pro-firebase',
    storageBucket: 'insta-pro-firebase.appspot.com',
    iosBundleId: 'com.example.instafirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy3mIM5cmflGRuVFMzsRkivzWUI7MZVhU',
    appId: '1:870228919490:ios:783176050047b5c9f8e75b',
    messagingSenderId: '870228919490',
    projectId: 'insta-pro-firebase',
    storageBucket: 'insta-pro-firebase.appspot.com',
    iosBundleId: 'com.example.instafirebase.RunnerTests',
  );
}
